//// USER const 
export const LOGIN_USER ='LOGIN_USER';
export const LOGOUT_USER ='LOGOUT_USER';
export const FETECHED_USER ='FETECHED_USER';
export const ADD_USER ='ADD_USER';
export const EDIT_USER ='EDIT_USER';
export const DELETE_USER_MESSAGE ='DELETE_USER_MESSAGE';
export const AUTH_USER ='AUTH_USER';
export const LOGIN_ERROR ='LOGIN_ERROR';
export const SIGNIN_USER_SUCCESS='SIGNIN_USER_SUCCESS';




/// PRODUCT const
export const GET_ALL_PRODUCTS='GET_ALL_PRODUCTS';
export const DELETE_PRODUCT='DELETE_PRODUCT';
export const EDIT_PRODUCT ='EDIT_PRODUCT';
export const ADD_PRODUCT ='ADD_PRODUCT';
export const GET_PRODUCT ='GET_PRODUCT';
export const GET_CLASSIC_PRODUCTS ='GET_CLASSIC_PRODUCTS';
export const GET_MODERN_PRODUCTS ='GET_MODERN_PRODUCTS';
export const GET_WOOD_PRODUCTS ='GET_WOOD_PRODUCTS';
export const GET_CERAMIC_PRODUCTS ='GET_CERAMIC_PRODUCTS';
export const ADD_BEST_PRODUCT ='ADD_BEST_PRODUCT';
export const GET_BEST_PRODUCTS ='GET_BEST_PRODUCTS';
export const DELETE_BEST_PRODUCT ='DELETE_BEST_PRODUCT';
export const GET_BEST_PRODUCT ='GET_BEST_PRODUCT';
export const GET_NB_PRODUCTS='GET_NB_PRODUCTS';
export const GET_NB_BEST_PRODUCTS='GET_NB_BEST_PRODUCTS';
export const GET_NB_CERAMIC_PRODUCTS='GET_NB_CERAMIC_PRODUCTS';
export const GET_NB_WOOD_PRODUCTS='GET_NB_WOOD_PRODUCTS';
export const NB_WOOD_CLASSIC_PRODUCTS='NB_WOOD_CLASSIC_PRODUCTS';
export const NB_CERAMIC_MODERN_PRODUCTS='NB_CERAMIC_MODERN_PRODUCTS';
export const NB_WOOD_MODERN_PRODUCTS='NB_WOOD_MODERN_PRODUCTS';
export const NB_CEREMIC_CLASSIC_PRODUCTS='NB_CEREMIC_CLASSIC_PRODUCTS';
export const NB_WOOD_WOOD_PRODUCTS='NB_WOOD_WOOD_PRODUCTS';
export const NB_CERAMIC_WOOD_PRODUCTS='NB_CERAMIC_WOOD_PRODUCTS';
export const NB_WOOD_CERAMIC_PRODUCTS='NB_WOOD_CERAMIC_PRODUCTS';
export const NB_CERAMIC_CERAMIC_PRODUCTS='NB_CERAMIC_CERAMIC_PRODUCTS';
export const PATCH_LIST_PRODUCT='PATCH_LIST_PRODUCT';
export const GET_BEST_SALES='GET_BEST_SALES';
export const DELETE_LIST_PRODUCT='DELETE_LIST_PRODUCT';





/// CLIENT const
export const GET_CLIENT='GET_CLIENT';
export const GET_NB_CLIENTS='GET_NB_CLIENTS';
export const GET_CLIENTS='GET_CLIENTS';




///Alert const
export const SHOW_MESSAGE='SHOW_MESSAGE';
export const HIDE_MESSAGE='HIDE_MESSAGE';
export const SHOW_Licence_MESSAGE='SHOW_Licence_MESSAGE';
export const HIDE_Licence_MESSAGE='HIDE_Licence_MESSAGE';
export const ON_SHOW_LOADER='ON_SHOW_LOADER';


////Orders const

export const GET_NB_ORDERS='GET_NB_ORDERS';
export const SEND_ORDER='SEND_ORDER';
export const GET_ORDERS='GET_ORDERS';
export const PATCH_SHIPPING_STATUS='PATCH_SHIPPING_STATUS';
export const SHOW_ORDER_MESSAGE='SHOW_ORDER_MESSAGE';
export const HIDE_ORDER_Licence_MESSAGE='HIDE_ORDER_Licence_MESSAGE';
export const HIDE_ORDER_MESSAGE='HIDE_ORDER_MESSAGE';
export const SHOW_ORDER_Licence_MESSAGE='SHOW_ORDER_Licence_MESSAGE';


///Cart const
export const ADD_TO_CART='ADD_TO_CART';
export const GET_FROM_CART='GET_FROM_CART';
export const GET_CART_ITEM='GET_CART_ITEM';
export const PATCH_QUANTITY='PATCH_QUANTITY';
export const ADD_ITEM_TO_CART='ADD_ITEM_TO_CART';

///Favoris const
export const ADD_TO_FAVORIS='ADD_TO_FAVORIS';
export const GET_FROM_FAVORIS='GET_FROM_FAVORIS';
export const GET_FAVORIS_ITEM='GET_FAVORIS_ITEM';
export const PATCH_FAVORIS_TAG='PATCH_FAVORIS_TAG';












